sudo: required
language: rust
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libssl-dev
cache: cargo
rust:
  - stable
  - nightly
env:
  global:
    - secure: "Gl2X2WmpUX/VKK1lXtiOP3NSl2EYS/nARUUEPCTNeR2KuIQNq/qf8/PEYAZCPO70tJKURmHxA84Zlb39YNMOkr3OfaYprlFfsChjI2FSwIFCDqmgruLAHDxpF9hMek+j3aUuRVxJoZLLdn0/uAZGabUIztZn9fUwBeVcjCzndWXu8x/A5M7zg+Gy2Gyy6ZN7LYIdQ2548wOz7QSS7gNFSktW+d7tK6+WArFwA+3WkF6iKXrEInV84K7EZg0+rE3l8ToscsGEsp/Lp96zDGR3vhKPSdqS2Sb6NkYgwbP8zr5HlwyA6QYGiMNd4O8mYhUrgMu2AmdBYBiOk1N/TuohGwwbCgtF+4yEIuhKG+9OeZXT1hp1B6ebcWLSQ37Vr2JIhteeQE2agEZ0Sb4T9QON0vzr30LCs+QtNpZpO46D9heYBzVgQpVyRPRXCAOA2nFV4vDb8GeW52r9pMMd5oYWg0NZonYCpDPaiBy7L612xSS2S/DlirbZTwjm77GeDWO7Iy2ccryxh6Rv+jXA5ZaFY+P8288CcNHlTbA6gMrKz32q9YI6nfdj3ObOgS1DWtnbmb3ldx+zaNz8H0/ktl2rxQEWG3uo4gePiNL/N2XBDo9+4JsASniy4/LBm8vF3lZlJygK7XfTijvulo63Dk0qZWS/jrYNkpu7N0rqwgyfGFQ="
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y mpd
  - /usr/bin/mpd --version
  - export PATH=$PATH:~/.cargo/bin
script:
  - cargo build
  - cargo test
  - cargo bench
after_success:
  - |
    if [[ "${TRAVIS_RUST_VERSION}" == stable ]]; then
      `RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin` 
      cargo tarpaulin --out Xml
      bash <(curl -s https://codecov.io/bash)
    fi
matrix:
  allow_failures:
    - rust: nightly
