[package]
name = "ncmpc"
version = "0.0.1"
authors = ["Benjamin Chrétien <chretien.b@gmail.com>"]

[dependencies]
mpd = "0.0.11"
ncurses = "5.80.0"
crossbeam = "0.2"

[lib]
name = "ncmpc"
path = "src/lib.rs"

[[bin]]
name = "ncmpc"
path = "src/main.rs"
