(function() {var implementors = {};
implementors["chrono"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"chrono/format/struct.Parsed.html\" title=\"struct chrono::format::Parsed\">Parsed</a>",synthetic:false,types:["chrono::format::parsed::Parsed"]},];
implementors["mpd"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"mpd/status/struct.Status.html\" title=\"struct mpd::status::Status\">Status</a>",synthetic:false,types:["mpd::status::Status"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"enum\" href=\"mpd/status/enum.State.html\" title=\"enum mpd::status::State\">State</a>",synthetic:false,types:["mpd::status::State"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"mpd/song/struct.Id.html\" title=\"struct mpd::song::Id\">Id</a>",synthetic:false,types:["mpd::song::Id"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"mpd/song/struct.QueuePlace.html\" title=\"struct mpd::song::QueuePlace\">QueuePlace</a>",synthetic:false,types:["mpd::song::QueuePlace"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"mpd/song/struct.Range.html\" title=\"struct mpd::song::Range\">Range</a>",synthetic:false,types:["mpd::song::Range"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"mpd/song/struct.Song.html\" title=\"struct mpd::song::Song\">Song</a>",synthetic:false,types:["mpd::song::Song"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"mpd/stats/struct.Stats.html\" title=\"struct mpd::stats::Stats\">Stats</a>",synthetic:false,types:["mpd::stats::Stats"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"mpd/search/struct.Query.html\" title=\"struct mpd::search::Query\">Query</a>&lt;'a&gt;",synthetic:false,types:["mpd::search::Query"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"mpd/client/struct.Client.html\" title=\"struct mpd::client::Client\">Client</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/net/tcp/struct.TcpStream.html\" title=\"struct std::net::tcp::TcpStream\">TcpStream</a>&gt;",synthetic:false,types:["mpd::client::Client"]},];
implementors["ncmpc"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"ncmpc/config/struct.KeyConfig.html\" title=\"struct ncmpc::config::KeyConfig\">KeyConfig</a>",synthetic:false,types:["ncmpc::config::KeyConfig"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"ncmpc/config/struct.ColorConfig.html\" title=\"struct ncmpc::config::ColorConfig\">ColorConfig</a>",synthetic:false,types:["ncmpc::config::ColorConfig"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"ncmpc/config/struct.ParamConfig.html\" title=\"struct ncmpc::config::ParamConfig\">ParamConfig</a>",synthetic:false,types:["ncmpc::config::ParamConfig"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"ncmpc/config/struct.Config.html\" title=\"struct ncmpc::config::Config\">Config</a>",synthetic:false,types:["ncmpc::config::Config"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"ncmpc/config/struct.ConfigLoader.html\" title=\"struct ncmpc::config::ConfigLoader\">ConfigLoader</a>",synthetic:false,types:["ncmpc::config::ConfigLoader"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"ncmpc/view/struct.PlaylistData.html\" title=\"struct ncmpc::view::PlaylistData\">PlaylistData</a>",synthetic:false,types:["ncmpc::view::PlaylistData"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
